import type { Metadata } from "next";
import { AuthProvider } from "@/providers/authProvider";
import { TrainerProvider } from "@/providers/trainerProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "NutriCoach",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <TrainerProvider>
        <html lang="en">
          <body>
            {children}
          </body>
        </html>
      </TrainerProvider>
    </AuthProvider>
  );
}